accounts/urls.py
from django.conf.urls import url
import django.contrib.auth.views

import accounts.views


urlpatterns = [

    url( r'^new_account$', accounts.views.new_account, name= 'new_account' ),
    url( r'^login$', accounts.views.login, name= 'login' ),
    url( r'^logout$', django.contrib.auth.views.logout, name= 'logout' ),
    url( r'^user/(?P<username>\w+)$', accounts.views.user_page, name= 'user_page' ),
    url( r'^user/(?P<username>\w+)/(?P<what>\w+)$', accounts.views.user_page, name= 'user_page_specify' ),
    url( r'^edit_account$', accounts.views.edit_account, name= 'edit' ),

        # Add/Remove Moderator Rights
    url( r'^set_moderator/confirm/(?P<username>\w+)$', accounts.views.set_moderator_confirm, name= 'set_moderator_confirm' ),
    url( r'^set_moderator/(?P<username>\w+)$', accounts.views.set_moderator, name= 'set_moderator' ),

        # Remove Account
    url( r'^remove/confirm/(?P<username>\w+)$', accounts.views.remove_user_confirm, name= 'remove_confirm' ),
    url( r'^remove/(?P<username>\w+)$', accounts.views.remove_user, name= 'remove' ),

        # Disable Account
    url( r'^disable/confirm/(?P<username>\w+)$', accounts.views.disable_user_confirm, name= 'disable_confirm' ),
    url( r'^disable/(?P<username>\w+)$', accounts.views.disable_user, name= 'disable' ),

        # Change Password
    url( r'^change_password$', django.contrib.auth.views.password_change, { 'template_name': 'accounts/change_password.html', 'post_change_redirect': 'accounts:password_changed' }, name= 'change_password' ),
    url( r'^password_changed$', accounts.views.password_changed, name= 'password_changed' ),

       # Private Messages
    url( r'^message/send/(?P<username>\w+)$', accounts.views.message_send, name= 'message_send' ),
    url( r'^message/all/$', accounts.views.message_all, name='message_all' ),
    url( r'^message/open/(?P<messageId>\w+)$', accounts.views.message_open, name= 'message_open' ),
    url( r'^message/remove_confirm/(?P<messageId>\w+)$', accounts.views.message_remove_confirm, name= 'message_remove_confirm' ),
    url( r'^message/remove/(?P<messageId>\w+)$', accounts.views.message_remove, name= 'message_remove' ),
]


microblog/urls.py
"""
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
"""
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

import microblog.views
import accounts.urls


urlpatterns = [

    url( r'^$', microblog.views.home, name= 'home' ),

    url( r'^post/add$', microblog.views.add_post, name= 'add_post' ),
    url( r'^post/remove$', microblog.views.remove_post, name= 'remove_post' ),
    url( r'^post/show/(?P<identifier>[\w-]+)$', microblog.views.show_post, name='show_post'),

    url( r'^follow/(?P<username>\w+)$', microblog.views.set_follow, name= 'follow' ),
    url( r'^category/(?P<categoryName>\w+)$', microblog.views.show_category, name= 'show_category' ),
    url( r'^people$', microblog.views.show_people, name= 'people' ),
    url( r'^categories$', microblog.views.show_categories, name= 'categories' ),
    url( r'^search$', microblog.views.search, name= 'search' ),

    url( r'^accounts/', include( accounts.urls, namespace= 'accounts', app_name= 'accounts' ) ),
    url( r'^admin/', include( admin.site.urls ) ),
]


    # serve the user related static files
urlpatterns += [
    url( r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    'document_root': settings.MEDIA_ROOT } ),
    ]


    # Serve static files when debug false
if not settings.DEBUG:
    urlpatterns += [
        url( r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT } ),
    ]

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.html import strip_tags


class FixUserCreationForm( UserCreationForm ):
    """
        The django form has the User hard-coded (so doesn't work with custom user models)

        Just change the parts where the User is hard-coded
    """
    def clean_username(self):

        userModel = get_user_model()
        username = self.cleaned_data[ "username" ]

        try:
            userModel.objects.get( username= username )

        except userModel.DoesNotExist:
            return username

        raise forms.ValidationError( self.error_messages[ 'duplicate_username' ] )


class MyUserCreationForm( FixUserCreationForm ):

    email = forms.EmailField( required= True )

    class Meta:

        model = get_user_model()
        fields = ( 'username', 'email', 'password1', 'password2' )

    def clean_email( self ):
        """
            Check if there's already an user with that email
        """
        userModel = get_user_model()
        email = self.cleaned_data[ 'email' ]

        try:
            userModel.objects.get( email= email )

        except userModel.DoesNotExist:
            return email

        else:
            raise ValidationError( 'An account with that email already exists.' )

    def save( self, commit= True ):

        user = super( MyUserCreationForm, self ).save( commit= False )
        user.email = self.cleaned_data[ 'email' ]

        if commit:
            user.save()

        return user


class PrivateMessageForm( forms.Form ):

    title = forms.CharField( max_length= 100 )
    content = forms.CharField( max_length= 500, widget= forms.Textarea )

    def clean_title(self):
        return strip_tags( self.cleaned_data[ 'title' ] )

    def clean_content(self):
        return strip_tags( self.cleaned_data[ 'content' ] )


class EditAccountForm( forms.Form ):

    name = forms.CharField( max_length= 30 )
    info = forms.CharField( max_length= 200, widget= forms.Textarea, required= False )
    image = forms.FileField( label= 'image', help_text= 'profile image', required= False )

accounts/views.py
from django.contrib.auth import get_user_model
from django.http import Http404, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login as django_login
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from accounts.forms import MyUserCreationForm, PrivateMessageForm, EditAccountForm
from accounts.models import PrivateMessage
from accounts.decorators import must_be_staff, must_be_moderator
from microblog import utilities


def new_account( request ):
    """
        Create a new user account.
    """
    if request.method == 'POST':

        form = MyUserCreationForm( request.POST )

        if form.is_valid():

            form.save()
            utilities.add_message( request, "User '{}' created!".format(  form.cleaned_data[ 'username' ] ) )

            return HttpResponseRedirect( reverse( 'accounts:login' ) )

    else:
        form = MyUserCreationForm()

    context = {
        'form': form
    }

    return render( request, 'accounts/new_account.html', context )


def login( request ):
    """
        Login an account.
    """
    context = {}
    utilities.get_messages( request, context )

    return django_login( request, 'accounts/login.html', extra_context= context )


def user_page( request, username, what= None ):
    """
        The user page has information about an user account.
        Also where you can change some settings (like the password).
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    context = {}

    if what == 'images':
        allElements = user.get_posts_with_images()
        context[ 'imagesSelected' ] = True

    elif what == 'followers':
        allElements = user.get_followers()
        context[ 'followersSelected' ] = True

    elif what == 'following':
        allElements = user.get_following()
        context[ 'followingSelected' ] = True

    else:   # 'messages'
        allElements = user.posts.all().order_by( '-date_created' )
        context[ 'postSelected' ] = True


    paginator = Paginator( allElements, 5 )
    page = request.GET.get( 'page' )

    try:
        elements = paginator.page( page )

    except PageNotAnInteger:
        elements = paginator.page( 1 )  # first page

    except EmptyPage:
        elements = paginator.page( paginator.num_pages )  # last page


    context.update({
        'pageUser': user,
        'unreadMessages': user.how_many_unread_messages(),
        'elements': elements,
    })

    utilities.get_messages( request, context )

    return render( request, 'accounts/user_page.html', context )


@login_required
def message_send( request, username ):
    """
        Send a private message to another user.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( 'Invalid username.' )


    if request.method == 'POST':
        form = PrivateMessageForm( request.POST )

        if form.is_valid():

            title = form.cleaned_data[ 'title' ]
            content = form.cleaned_data[ 'content' ]
            PrivateMessage.objects.create( receiver= user, sender= request.user, title= title, content= content )

            utilities.add_message( request, 'Message sent to {}!'.format( user ) )

            return HttpResponseRedirect( user.get_url() )

    else:
        form = PrivateMessageForm()

    context = {
        'form': form,
        'receiver': user
    }

    return render( request, 'accounts/send_message.html', context )


@login_required
def message_all( request ):
    """
        Get a list of all the private messages available.
    """
    messages = request.user.privatemessage_set.all()

    context = {
        'messages': messages
    }

    utilities.get_messages( request, context )

    return render( request, 'accounts/check_messages.html', context )


@login_required
def message_open( request, messageId ):
    """
        Open a particular private message.
    """
    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Couldn't find that message." )

    if not message.has_been_read:
        message.has_been_read = True
        message.save( update_fields= [ 'has_been_read' ] )

    context = {
        'private_message': message
    }

    return render( request, 'accounts/open_message.html', context )


@login_required
def message_remove_confirm( request, messageId ):
    """
        Confirm the message removal.
    """
    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Didn't find the message." )

    else:
        context = {
            'private_message': message
        }

        return render( request, 'accounts/remove_message.html', context )


@login_required
def message_remove( request, messageId ):
    """
        Remove a private message.
    """
    try:
        message = request.user.privatemessage_set.get( id= messageId )

    except PrivateMessage.DoesNotExist:
        raise Http404( "Message doesn't exist." )

    message.delete()
    utilities.add_message( request, 'Message removed!' )

    return HttpResponseRedirect( reverse( 'accounts:message_all' ) )


@must_be_staff
def set_moderator_confirm( request, username ):
    """
        Confirm giving/removing moderator rights to/from an user.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        context = {
            'user_to_change': user
        }
        return render( request, 'accounts/change_moderator.html', context )


@must_be_staff
def set_moderator( request, username ):
    """
        Give/remove moderator rights from an account.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    user.is_moderator = not user.is_moderator
    user.save( update_fields= [ 'is_moderator' ] )

    if user.is_moderator:
        message = "'{}' is now a moderator.".format( user )

    else:
        message = "'{}' is not a moderator anymore.".format( user )

    utilities.add_message( request, message )

    return HttpResponseRedirect( user.get_url() )


def password_changed( request ):
    """
        Inform that the password has been changed, and redirect to home.
    """
    utilities.add_message( request, 'Password changed!' )

    return HttpResponseRedirect( reverse( 'home' ) )


@login_required
def edit_account( request ):
    """
        Page where some information about the user can be changed.
    """
    if request.method == 'POST':

        form = EditAccountForm( request.POST, request.FILES )

        if form.is_valid():

            name = form.cleaned_data[ 'name' ]
            info = form.cleaned_data[ 'info' ]
            image = request.FILES.get( 'image' )

            request.user.name = name
            request.user.info = info

            if image:
                request.user.image = image

            request.user.save( update_fields= [ 'name', 'info', 'image' ] )

            return HttpResponseRedirect( request.user.get_url() )

    else:
        form = EditAccountForm( initial= { 'name': request.user.name, 'info': request.user.info } )

    context = {
        'form': form
    }

    return render( request, 'accounts/edit_account.html', context )


@must_be_staff
def remove_user_confirm( request, username ):
    """
        Confirm an user removal.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    context = {
        'user_to_remove': user
    }

    return render( request, 'accounts/remove_user.html', context )


@must_be_staff
def remove_user( request, username ):
    """
        Remove an user account (also removes everything associated with it).
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        utilities.add_message( request, "'{}' user removed!".format( user ) )
        user.delete()

        return HttpResponseRedirect( reverse( 'home' ) )


@must_be_moderator
def disable_user_confirm( request, username ):
    """
        Confirm the enabling/disabling of an user account.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        context = {
            'user_to_disable': user
        }

        return render( request, 'accounts/disable_user.html', context )


@must_be_moderator
def disable_user( request, username ):
    """
        Enable/disable an user account.
        If the account is disabled, the user won't be able to login.
    """
    userModel = get_user_model()

    try:
        user = userModel.objects.get( username= username )

    except userModel.DoesNotExist:
        raise Http404( "User doesn't exist." )

    else:
        value = not user.is_active

            # only other staff users can enable/disable staff users
        if user.is_staff:
            if request.user.is_staff:
                user.is_active = value
                user.save( update_fields= [ 'is_active' ] )

            else:

templates/accounts/change_moderator.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}

{% if user_to_change.is_moderator %}
    <h2>Remove moderator rights from {{ user_to_change|account_name }}?</h2>
{% else %}
    <h2>Give moderator rights to {{ user_to_change|account_name }}?</h2>
{% endif %}

<p>
    <a href="{% url 'accounts:set_moderator' user_to_change.username %}">Yes</a>
    <a href="{{ user_to_change.get_url }}">No</a>
</p>

{% endblock %}

templates/accounts/change_password.html
{% extends "base.html" %}
{% load microblog_filters %}

{% block content %}

<h2>Change password</h2>

{% if form.errors %}
    <p>{{ form.errors }}</p>
{% endif %}

<form method="post" action="{% url 'accounts:change_password' %}">
    {% csrf_token %}

    <table>
        <tr>
            <td>{{ form.old_password.label_tag }}</td>
            <td>{{ form.old_password|add_css_class:"form-control" }}</td>
        </tr>
        <tr>
            <td>{{ form.new_password1.label_tag }}</td>
            <td>{{ form.new_password1|add_css_class:"form-control" }}</td>
        </tr>
        <tr>
            <td>{{ form.new_password2.label_tag }}</td>
            <td>{{ form.new_password2|add_css_class:"form-control" }}</td>
        </tr>
    </table>

    <input type="submit" value="change" class="btn btn-default" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/accounts/check_messages.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}
{% load static %}


{% block scripts %}
    <script type="text/javascript" src="{% static 'js/check_messages.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/tooltip.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/sort_table.js' %}"></script>
{% endblock %}


{% block content %}

<h2>Private messages</h2>

{% if messages %}

    <table id="CheckMessagesTable" class="SortTable">
        <thead>
            <tr>
                <th class="SortTable-sortable">from</th>
                <th class="SortTable-sortable">title</th>
                <th class="SortTable-sortable" data-initial-sort="ascending">date</th>
            </tr>
        </thead>

        <tbody>
        {% for message in messages %}
            <tr class="clickableRow contentPreview" data-url="{{ message.get_url }}" data-content="{{ message.content|linebreaksbr|truncatewords:50 }}">
                <td data-value="{{ message.sender }}">
                    {% if not message.has_been_read %}
                        <span class="red" title="Unread message!">!</span>
                    {% endif %}

                    {{ message.sender|account_name }}
                </td>
                <td data-value="{{ message.title.strip|truncatewords:25 }}">{{ message.title|truncatewords:25 }}</td>
                <td data-value="{{ message.get_date_created_number }}">{{ message.date_created|naturaltime }}</td>
                <td><a href="{% url 'accounts:message_remove_confirm' message.id %}" title="Remove Message">X</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% else %}
    <p>No messages.</p>
{% endif %}

{% endblock %}

templates/accounts/disable_user.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}

{% if user_to_disable.is_active %}
    <h2>Disable user: {{ user_to_disable|account_name }}?</h2>
{% else %}
    <h2>Enable user: {{ user_to_disable|account_name }}?</h2>
{% endif %}

<p>
    <a href="{% url 'accounts:disable' user_to_disable.username %}">Yes</a>
    <a href="{{ user_to_disable.get_url }}">No</a>
</p>

{% endblock %}

templates/accounts/edit_account.html
{% extends "base.html" %}
{% load microblog_filters %}

{% block content %}

<h2>{{ user.username }}</h2>

{% if user.image %}
    <img src="{{ MEDIA_URL }}{{ user.image }}" class="profileImage" />
{% else %}
    <p>no profile image.</p>
{% endif %}

<ul>
    <li><a href="{% url 'accounts:change_password' %}">change password</a></li>
</ul>


<h4>Update account</h4>

{% if form.errors %}
    <table>
        {% for field in form %}
            <tr>
                <td>{{ field.name }}</td>
                <td>{{ field.errors }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}

<form method="post" action="{% url 'accounts:edit' %}" enctype="multipart/form-data">
    {% csrf_token %}

    <table>
        <tr>
            <td>{{ form.name.label_tag }}</td>
            <td>{{ form.name|add_css_class:"form-control" }}</td>
        </tr>
        <tr>
            <td>{{ form.info.label_tag }}</td>
            <td>{{ form.info|add_css_class:"form-control" }}</td>
        </tr>
        <tr>
            <td>{{ form.image.label_tag }}</td>
            <td>{{ form.image }}</td>
        </tr>
    </table>

    <input type="submit" value="update" class="btn btn-default" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>


{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}
{% load microblog_filters %}

{% block content %}

<h1>Login</h1>

{% if form.errors %}
    <p>Wrong username/password.</p>
{% endif %}

<form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}

    <table>
        <tr>
            <td>{{ form.username.label_tag }}</td>
            <td>{{ form.username|add_css_class:"form-control" }}</td>
        </tr>
        <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password|add_css_class:"form-control" }}</td>
        </tr>
    </table>

    <input type="submit" value="login" class="btn btn-default" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

<br /><br />

<p>
    <a href="{% url 'accounts:new_account' %}">Create a new account.</a>
</p>


{% endblock %}

templates/accounts/new_account.html
{% extends "base.html" %}
{% load microblog_filters %}

{% block content %}

    <h1>Create a new user</h1>

    {% if form.errors %}
        <table>
            {% for field in form %}
                <tr>
                    <td>{{ field.name }}</td>
                    <td>{{ field.errors }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}

    <form method="post" action="{% url 'accounts:new_account' %}">
        {% csrf_token %}

        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username|add_css_class:"form-control" }}</td>
            </tr>
            <tr>
                <td>{{ form.email.label_tag }}</td>
                <td>{{ form.email|add_css_class:"form-control" }}</td>
            </tr>
            <tr>
                <td>{{ form.password1.label_tag }}</td>
                <td>{{ form.password1|add_css_class:"form-control" }}</td>
            </tr>
            <tr>
                <td>{{ form.password2.label_tag }}</td>
                <td>{{ form.password2|add_css_class:"form-control" }}</td>
            </tr>
        </table>

        <input type="submit" value="create" class="btn btn-default" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>

{% endblock %}

templates/accounts/open_message.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}

<p>From <a href="{{ private_message.sender.get_url }}">{{ private_message.sender }}</a> {{ private_message.date_created|naturaltime }}</p>

<h2>{{ private_message.title }}</h2>

<p>{{ private_message.content|linebreaksbr }}</p>

<a href="{% url 'accounts:send_message' private_message.sender %}">reply</a>
<a href="{% url 'accounts:check_message' %}">back</a>

{% endblock %}

templates/accounts/remove_message.html
{% extends "base.html" %}
{% load humanize %}
{% load accounts %}

{% block content %}

<p>From {{ private_message.sender|account_name }} {{ private_message.date_created|naturaltime }}</p>

<h2 id="PrivateMessage-title">{{ private_message.title }}</h2>

<p>{{ private_message.content|linebreaksbr }}</p>


<p>Remove private message? <a href="{% url 'accounts:message_remove' private_message.id %}">Yes</a> <a href="{% url 'accounts:message_all' %}">No</a></p>

{% endblock %}

templates/accounts/remove_user.html
{% extends "base.html" %}
{% load accounts %}

{% block content %}
<h2>Remove user: {{ user_to_remove|account_name }}?</h2>

<p>
    <a href="{% url 'accounts:remove' user_to_remove.username %}">Yes</a>
    <a href="{{ user_to_remove.get_url }}">No</a>
</p>
{% endblock %}

templates/accounts/send_message.html
{% extends "base.html" %}
{% load accounts %}
{% load microblog_filters %}

{% block content %}

<h2>Send message to {{ receiver|account_name }}</h2>

{% if form.errors %}
    <p>{{ form.errors }}</p>
{% endif %}

<form method="post" action="{% url 'accounts:message_send' receiver.username %}">
    {% csrf_token %}

    <table>
        <tr>
            <td>{{ form.title.label_tag }}</td>
            <td>{{ form.title|add_css_class:"form-control" }}</td>
        </tr>
        <tr>
            <td>{{ form.content.label_tag }}</td>
            <td>{{ form.content|add_css_class:"form-control" }}</td>
        </tr>
    </table>

    <input type="submit" value="send" class="btn btn-default" />
    <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

templates/accounts/user_page.html
{% extends "base.html" %}
{% load humanize %}
{% load microblog_filters %}
{% load accounts %}

{% block content %}

    <h2>
        {{ pageUser.name }} ({{ pageUser|account_name }})

        <ul class="horizontalList">
            {% if user.is_moderator or user.is_staff %}
            <li>
                <a href="{% url 'accounts:disable_confirm' pageUser.username %}">
                    {% if pageUser.is_active %}
                        disable
                    {% else %}
                        enable
                    {% endif %}
                </a>
            </li>
            {% endif %}

            {% if user.is_staff %}
            <li>
                <a href="{% url 'accounts:set_moderator_confirm' pageUser.username %}">
                    {% if pageUser.is_moderator %}
                        un-mod
                    {% else %}
                        mod
                    {% endif %}
                </a>
            </li>
            <li>
                <a href="{% url 'accounts:remove_confirm' pageUser.username %}">remove</a>
            </li>
            {% endif %}

            {% if user.is_authenticated %}
            {% if user.username != pageUser.username %}
                <li>
                    <a href="{% url 'follow' pageUser.username %}?next={{ request.get_full_path|urlencode }}">
                        {% if request.user|is_following:pageUser.username %}
                            un-follow
                        {% else %}
                            follow
                        {% endif %}
                    </a>
                </li>
            {% else %}
                <li><a href="{% url 'accounts:edit' %}">edit account</a></li>
            {% endif %}
            {% endif %}
        </ul>
    </h2>

    {% if pageUser.image %}
        <img class="profileImage" src="{{ MEDIA_URL }}{{ pageUser.image }}" />
    {% endif %}

    <p>User since: {{ pageUser.date_joined }} ({{ pageUser.date_joined|naturaltime }})</p>

    <p>{{ pageUser.info }}</p>

    {% if user.is_authenticated %}
    <ul>
    {% if user.username != pageUser.username %}
        <li><a href="{% url 'accounts:message_send' pageUser.username %}">Send private message.</a></li>
    {% else %}
        <li><a href="{% url 'accounts:message_all' %}">See private messages
            {% if unreadMessages %}
                (<em>{{ unreadMessages }}</em> unread)
            {% endif %}
        </a></li>
    {% endif %}
    </ul>
    {% endif %}


<ul class="horizontalList">
    <li {% if postSelected %}class="entrySelected"{% endif %}>
        <a href="{{ pageUser.get_url }}">posts: {{ pageUser.posts.count }}</a>
    </li>
    <li {% if imagesSelected %}class="entrySelected"{% endif %}>
        <a href="{% url 'accounts:user_page_specify' pageUser.username "images" %}">images: {{ pageUser.get_images_count }}</a>
    </li>
    <li {% if followersSelected %}class="entrySelected"{% endif %}>
        <a href="{% url 'accounts:user_page_specify' pageUser.username "followers" %}">Followers: {{ pageUser.get_followers.count }}</a>
    </li>
    <li {% if followingSelected %}class="entrySelected"{% endif %}>
        <a href="{% url 'accounts:user_page_specify' pageUser.username "following" %}">Following: {{ pageUser.get_following.count }}</a>
    </li>
</ul>

{% if postSelected or imagesSelected %}
    {% include "posts.html" with posts=elements %}
{% elif followersSelected or followingSelected %}
    {% include "users.html" with users=elements %}
{% endif %}

{% endblock %}