accounts/urls.py
from django.conf.urls import url
import django.contrib.auth.views

import accounts.views


urlpatterns = [

    url( r'^new_account$', accounts.views.new_account, name= 'new_account' ),
    url( r'^login$', accounts.views.login, name= 'login' ),
    url( r'^logout$', django.contrib.auth.views.logout, name= 'logout' ),
    url( r'^user/(?P<username>\w+)$', accounts.views.user_page, name= 'user_page' ),
    url( r'^user/(?P<username>\w+)/(?P<what>\w+)$', accounts.views.user_page, name= 'user_page_specify' ),
    url( r'^edit_account$', accounts.views.edit_account, name= 'edit' ),

        # Add/Remove Moderator Rights
    url( r'^set_moderator/confirm/(?P<username>\w+)$', accounts.views.set_moderator_confirm, name= 'set_moderator_confirm' ),
    url( r'^set_moderator/(?P<username>\w+)$', accounts.views.set_moderator, name= 'set_moderator' ),

        # Remove Account
    url( r'^remove/confirm/(?P<username>\w+)$', accounts.views.remove_user_confirm, name= 'remove_confirm' ),
    url( r'^remove/(?P<username>\w+)$', accounts.views.remove_user, name= 'remove' ),

        # Disable Account
    url( r'^disable/confirm/(?P<username>\w+)$', accounts.views.disable_user_confirm, name= 'disable_confirm' ),
    url( r'^disable/(?P<username>\w+)$', accounts.views.disable_user, name= 'disable' ),

        # Change Password
    url( r'^change_password$', django.contrib.auth.views.password_change, { 'template_name': 'accounts/change_password.html', 'post_change_redirect': 'accounts:password_changed' }, name= 'change_password' ),
    url( r'^password_changed$', accounts.views.password_changed, name= 'password_changed' ),

       # Private Messages
    url( r'^message/send/(?P<username>\w+)$', accounts.views.message_send, name= 'message_send' ),
    url( r'^message/all/$', accounts.views.message_all, name='message_all' ),
    url( r'^message/open/(?P<messageId>\w+)$', accounts.views.message_open, name= 'message_open' ),
    url( r'^message/remove_confirm/(?P<messageId>\w+)$', accounts.views.message_remove_confirm, name= 'message_remove_confirm' ),
    url( r'^message/remove/(?P<messageId>\w+)$', accounts.views.message_remove, name= 'message_remove' ),
]


microblog/urls.py
"""
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
"""
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

import microblog.views
import accounts.urls


urlpatterns = [

    url( r'^$', microblog.views.home, name= 'home' ),

    url( r'^post/add$', microblog.views.add_post, name= 'add_post' ),
    url( r'^post/remove$', microblog.views.remove_post, name= 'remove_post' ),
    url( r'^post/show/(?P<identifier>[\w-]+)$', microblog.views.show_post, name='show_post'),

    url( r'^follow/(?P<username>\w+)$', microblog.views.set_follow, name= 'follow' ),
    url( r'^category/(?P<categoryName>\w+)$', microblog.views.show_category, name= 'show_category' ),
    url( r'^people$', microblog.views.show_people, name= 'people' ),
    url( r'^categories$', microblog.views.show_categories, name= 'categories' ),
    url( r'^search$', microblog.views.search, name= 'search' ),

    url( r'^accounts/', include( accounts.urls, namespace= 'accounts', app_name= 'accounts' ) ),
    url( r'^admin/', include( admin.site.urls ) ),
]


    # serve the user related static files
urlpatterns += [
    url( r'^media/(?P<path>.*)$', 'django.views.static.serve', {
    'document_root': settings.MEDIA_ROOT } ),
    ]


    # Serve static files when debug false
if not settings.DEBUG:
    urlpatterns += [
        url( r'^static/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT } ),
    ]

templates/_post.html
{% load humanize %}
{% load microblog_filters %}

<tr class="post{% if post_class %} {{ post_class }}{% endif %}" {% if post_id %}id="{{ post_id }}"{% endif %}>
    <td class="postProfileImage">
    {% if post.user.image %}
        <img src="{{ MEDIA_URL }}{{ post.user.image }}" />
    {% endif %}
    </td>
    <td class="postText">
        <div>
            <a href="{{ post.user.get_url }}">{{ post.user.name }} ({{ post.user.username }})</a> {{ post.date_created|naturaltime }}
        </div>
        <div class="postText-content">
            {{ post.text|category_links }}
            <div>
                {% if post.image %}
                    <img src="{{ MEDIA_URL }}{{ post.image }}" />
                {% endif %}
            </div>
        </div>
        <div>
            <ul class="horizontalList">
                {% if request.user.is_authenticated %}
                    <li><a href="#" onclick="WebSite.openPostDialog('{{ post.identifier }}');">reply</a></li>
                {% endif %}
                <li>
                    <a href="{{ post.get_url }}">open</a>
                    {% if post.replies %}
                        ({{ post.replies.count }})
                    {% endif %}
                </li>
                {% if request.user == post.user %}
                    <li><a href="#" onclick="WebSite.openRemoveDialog('{{ post.identifier }}');">remove</a></li>
                {% endif %}
            </ul>
        </div>
    </td>
</tr>

templates/base.html
{% load static %}
{% load accounts %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>micro-blog</title>

    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="{% static 'js/website.js' %}"></script>

    {% block scripts %}{% endblock %}

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>

<nav id="Menu" class="navbar navbar-default" role="navigation">
    <ul class="nav navbar-nav">
        <li><a href="{% url 'home' %}">home</a></li>

        {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:user_page' user.username %}">{{ user.username }}</a></li>
            <li><a href="{% url 'accounts:logout' %}?next={{ request.get_full_path|urlencode }}">logout</a></li>
        {% else %}
            <li><a href="{% url 'accounts:login' %}?next={{ request.get_full_path|urlencode }}">login</a></li>
        {% endif %}

        <li><a href="{% url 'people' %}">find people</a></li>
        <li><a href="{% url 'categories' %}">categories</a></li>

        {% if user.is_authenticated %}
            <li><button id="PostButton" type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#PostDialog">post</button></li>
        {% endif %}
    </ul>


    <form method="post" action="{% url 'search' %}" class="navbar-form navbar-right" id="SearchForm">
        {% csrf_token %}

        <input id="SearchText" name="SearchText" type="text" class="form-control" />
        <input type="submit" value="search" class="btn btn-default" />
    </form>
</nav>

<div id="MessagesContainer">
    {% for message in MESSAGES %}
        <p class="Message Message-{{ message.type }}" title="Click to Remove" onclick="WebSite.removeElement(this);">{{ message.message }}</p>
    {% endfor %}
</div>

<div id="PostDialog" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <textarea id="PostText" maxlength="{{ post_max_length }}"></textarea>
            </div>
            <div class="modal-footer">
                <input id="PostImage" type="file" />

                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="WebSite.addPost(event);">Post</button>
            </div>
        </div>
    </div>
</div>

<div id="RemoveDialog" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                Remove the post?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-primary" onclick="WebSite.removePost(event);">Yes</button>
            </div>
        </div>
    </div>
</div>


{% block content %}{% endblock %}

</body>
</html>

templates/categories.html
{% extends "base.html" %}

{% block content %}

<h1>Categories</h1>

{% if categories %}
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Post Count</th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
            <tr>
                <td><a href="{{ category.get_url }}">{{ category.name }}</a></td>
                <td>{{ category.posts_count }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if categories.has_previous %}
        <a href="{{ request.path|urlencode }}?page={{ categories.previous_page_number }}">previous</a>
    {% endif %}
    {% if categories.number %}
        <span>Page {{ categories.number }} of {{ categories.paginator.num_pages }}</span>
    {% endif %}
    {% if categories.has_next %}
        <a href="{{ request.path|urlencode }}?page={{ categories.next_page_number }}">next</a>
    {% endif %}
{% else %}
    <p>No categories yet.</p>
{% endif %}

{% endblock %}

templates/category.html
{% extends "base.html" %}
{% load humanize %}
{% load microblog_filters %}

{% block content %}

<h1 id="CategoryHeader">{{ categoryName }}</h1>

{% include "posts.html" %}

{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}

{% include "posts.html" %}

{% endblock %}

templates/people.html
{% extends "base.html" %}
{% load microblog_filters %}

{% block content %}

<h1>People</h1>

{% include "users.html" %}

{% endblock %}

templates/posts.html
{% load humanize %}
{% load microblog_filters %}

{% if posts %}
    <table id="PostTable">
        {% for post in posts %}
            {% if post == selected_post %}
                {% include "_post.html" with post=post post_id="SelectedPost" %}

                {% for reply in replies %}
                    {% include "_post.html" with post=reply post_class="replyPost" %}
                {% endfor %}
            {% else %}
                {% include "_post.html" with post=post %}
            {% endif %}
        {% endfor %}
    </table>

    {% if posts.has_previous %}
        <a href="{{ request.path|urlencode }}?page={{ posts.previous_page_number }}">previous</a>
    {% endif %}
    {% if posts.number %}
        <span>Page {{ posts.number }} of {{ posts.paginator.num_pages }}</span>
    {% endif %}
    {% if posts.has_next %}
        <a href="{{ request.path|urlencode }}?page={{ posts.next_page_number }}">next</a>
    {% endif %}
{% else %}
    <p>No posts yet. Try to follow <a href="{% url 'people' %}">some people.</a></p>
{% endif %}

templates/search.html
{% extends "base.html" %}

{% block content %}

<p>Searched for: {{ search }}</p>

<h2>People</h2>

{% if people %}
    {% for person in people %}
    <ul>
        <li><a href="{{ person.get_url }}">{{ person }}</a></li>
    </ul>
    {% endfor %}
{% else %}
    <p>Nothing found.</p>
{% endif %}

<h2>Categories</h2>

{% if categories %}
    {% for category in categories %}
    <ul>
        <li><a href="{{ category.get_url }}">{{ category }}</a></li>
    </ul>
    {% endfor %}
{% else %}
    <p>Nothing found.</p>
{% endif %}

<h2>Posts</h2>

{% if posts %}
    {% for post in posts %}
    <ul>
        <li><a href="{{ post.get_url }}">{{ post }}</a></li>
    </ul>
    {% endfor %}
{% else %}
    <p>Nothing found.</p>
{% endif %}

{% endblock %}

templates/show_message.html
{% extends "base.html" %}

{% block content %}

    {% include "messages.html" %}

{% endblock %}

templates/show_post.html
{% extends "base.html" %}

{% block content %}

    {% include "posts.html" %}

{% endblock %}

templates/users.html
{% load microblog_filters %}

{% if users %}
    <table>
        {% for user in users %}
        <tr>
            <td class="postProfileImage">
            {% if user.image %}
                <img src="{{ MEDIA_URL }}{{ user.image }}" />
            {% endif %}
            </td>
            <td><a href="{{ user.get_url }}">{{ user.username }}</a></td>
            <td>{{ user.info }}</td>
            <td>
                {% if request.user == user %}
                    ---
                {% else %}
                    <a href="{% url 'follow' user.username %}?next={{ request.get_full_path|urlencode }}">
                        {% if request.user|is_following:user.username %}
                            un-follow
                        {% else %}
                            follow
                        {% endif %}
                    </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>

    {% if users.has_previous %}
        <a href="{{ request.path|urlencode }}?page={{ users.previous_page_number }}">previous</a>
    {% endif %}
    {% if users.number %}
        <span>Page {{ users.number }} of {{ users.paginator.num_pages }}</span>
    {% endif %}
    {% if users.has_next %}
        <a href="{{ request.path|urlencode }}?page={{ users.next_page_number }}">next</a>
    {% endif %}
{% else %}
    <p>Didn't find anyone.</p>
{% endif %}